RabbitMQ
prjctr-node/ride-service pull request #11
Opened 2021-05-23 20:33 UTC by VladSmorodsky

2021-05-24 11:37 UTC, welikoiwanenko requested changes
В целом - 🔥, надо пару моментов исправить

2021-05-24 11:37 UTC, welikoiwanenko commented on .env_default
> +AMQP=amqp://localhost
```
AMQP_HOST=localhost
```

2021-05-24 11:37 UTC, welikoiwanenko commented on src/middlewares/amqp.js
> +    console.log(status);
console.log's

2021-05-24 11:37 UTC, welikoiwanenko commented on src/middlewares/amqp.js
> +        console.log('[data]', data);
console.log

2021-05-24 11:37 UTC, welikoiwanenko commented on src/middlewares/routes/reviews.js
> +  ctx.amqp.publish('TEST RIDE REVIEW', 'ride_review');
?

2021-05-24 11:37 UTC, welikoiwanenko commented on src/middlewares/amqp.js
> +const EXCHANGE_NAME = 'prjctr_exchange';
Как и обсуждали - надо поменять

2021-05-24 12:04 UTC, VladSmorodsky commented on .env_default
> +AMQP=amqp://localhost
Fixed

2021-05-24 12:04 UTC, VladSmorodsky commented on src/middlewares/amqp.js
> +    console.log(status);
Removed

2021-05-24 12:04 UTC, VladSmorodsky commented on src/middlewares/amqp.js
> +        console.log('[data]', data);
Removed

2021-05-24 12:05 UTC, VladSmorodsky commented on src/middlewares/routes/reviews.js
> +  ctx.amqp.publish('TEST RIDE REVIEW', 'ride_review');
Абсолютное недоразумение и крайняя степень отчаяния)
 FIxed

2021-05-24 12:05 UTC, VladSmorodsky commented on src/middlewares/amqp.js
> +const EXCHANGE_NAME = 'prjctr_exchange';
Fixed

2021-05-25 18:48 UTC, welikoiwanenko requested changes
Остались мелочи

2021-05-25 18:48 UTC, welikoiwanenko commented on src/index.js
>  console.log(a);
Уберёшь тут заодно?)

2021-05-25 18:48 UTC, welikoiwanenko commented on config/default.js
> +  amqp: process.env.AMQP,
Тут тоже надо поменять

2021-05-25 18:48 UTC, welikoiwanenko commented on src/middlewares/amqp.js
> +    const connection = await amqp.connect(config.AMQP_HOST);
```
(`amqp://${config.AMQP_HOST}`)
```

2021-05-25 19:01 UTC, welikoiwanenko approved these changes

2021-05-25 19:02 UTC, merged