Dev
prjctr-node/ride-service pull request #2
Opened 2021-04-13 17:56 UTC by VladSmorodsky

2021-04-13 19:40 UTC, welikoiwanenko commented
Отдельный огромный лайк, что сделали всё вместе!)

2021-04-13 19:49 UTC, welikoiwanenko requested changes
Выглядит супер, есть пара моментов to change

2021-04-13 19:49 UTC, welikoiwanenko commented on .eslintignore
> +node_modules
nit: не забывайте добавлять в конце строки перенос

2021-04-13 19:49 UTC, welikoiwanenko commented on package.json
> +  "scripts": {
Добавьте ещё скрипт start

2021-04-13 19:49 UTC, welikoiwanenko commented on .eslintrc.js
> +    'max-len': ['error', 100, 2, { ignoreUrls: true }],
Длинна в 100 конфликтует с 120 в конфиге prettier

2021-04-13 19:49 UTC, welikoiwanenko commented on src/middlewares/routes.js
> +      ctx.res.statusCode = 200;
ctx.status - можно короче😉

2021-04-13 19:49 UTC, welikoiwanenko commented on src/index.js
> +app.use(async (ctx, next) => {
Вполне рабочий вариант, но я бы предпочёл в это строке лаконичное
```
app.use(routes.router())
```

2021-04-13 19:49 UTC, welikoiwanenko commented on src/index.js
> +app.use(async (ctx, next) => {
Как пример - можно глянуть как реализован koa-logger

2021-04-14 10:14 UTC, birth-mark commented on .eslintignore
> +node_modules
fixed

2021-04-14 10:14 UTC, birth-mark commented on .eslintrc.js
> +    'max-len': ['error', 100, 2, { ignoreUrls: true }],
fixed

2021-04-14 10:14 UTC, birth-mark commented on package.json
> +  "scripts": {
fixed

2021-04-14 10:14 UTC, birth-mark commented on src/middlewares/routes.js
> +      ctx.res.statusCode = 200;
fixed

2021-04-14 16:05 UTC, birth-mark commented on src/index.js
> +app.use(async (ctx, next) => {
fixed

2021-04-15 08:58 UTC, welikoiwanenko commented on src/middlewares/routes.js
> +  if (route !== undefined) {
if (!route)

2021-04-15 09:39 UTC, welikoiwanenko approved these changes

2021-04-15 12:03 UTC, birth-mark commented on src/middlewares/routes.js
> +  if (route !== undefined) {
fixed

2021-04-15 12:05 UTC, merged